# AppVeyor Configuration v5.4 - Schema-Validated
image: Visual Studio 2022

environment:
  APP_URL: "https://github.com/Izaacapp/SilverBulletPro-Docker/releases/download/blessed/SilverBulletPro-v1.5.8.rar"

install:
  - ps: mkdir app_workspace | Out-Null
  - ps: cd app_workspace
  - ps: Invoke-WebRequest -Uri $env:APP_URL -OutFile "app.rar"
  - ps: 7z x app.rar -aoa -y
  - ps: Remove-Item app.rar -Force
  - ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
  - ps: ./dotnet-install.ps1 -Channel 8.0 -Runtime windowsdesktop
  - ps: Remove-Item dotnet-install.ps1 -Force

build_script:
  - ps: |
      $requiredFiles = @("SilverBulletPro.exe", "SilverBulletPro.dll", "appsettings.json")
      $missingFiles = $requiredFiles | Where-Object { -not (Test-Path $_) }
      if ($missingFiles) { throw "Missing required files: $($missingFiles -join ', ')" }

artifacts:
  - path: 'app_workspace\*'
    name: SilverBulletPro-Prepared
    type: Zip