# AppVeyor Configuration v4.4 - Final Artifact Path
# This is the definitive, working configuration.

image: Visual Studio 2022

environment:
  APP_URL: "https://github.com/Izaacapp/SilverBulletPro-Docker/releases/download/blessed/SilverBulletPro-v1.5.8.rar"

install:
  - ps: echo "Downloading application..."
  - ps: Invoke-WebRequest -Uri $env:APP_URL -OutFile "app.rar"
  - ps: echo "Extracting application..."
  - ps: 7z x app.rar -aoa -y
  - ps: echo "Installing .NET 8 Desktop Runtime..."
  - ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
  - ps: ./dotnet-install.ps1 -Channel 8.0 -Runtime windowsdesktop

build_script:
  - cmd: echo "Setup complete. Verifying executable exists..."
  - cmd: dir SilverBulletPro.exe

artifacts:
  # --- THE FINAL FIX ---
  # We provide the full, explicit path to the project directory.
  # AppVeyor clones projects into C:\projects\<repository-name> by default.
  - path: 'C:\projects\silverbulletpro-docker'
    name: SilverBulletPro-Prepared