# AppVeyor Configuration v4.3 - Final path correction

image: Visual Studio 2022

environment:
  APP_URL: "https://github.com/Izaacapp/SilverBulletPro-Docker/releases/download/blessed/SilverBulletPro-v1.5.8.rar"

install:
  - ps: echo "Downloading application..."
  - ps: Invoke-WebRequest -Uri $env:APP_URL -OutFile "app.rar"
  - ps: echo "Extracting application..."
  - ps: 7z x app.rar -aoa -y
  - ps: echo "Installing .NET 8 Desktop Runtime..."
  - ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
  - ps: ./dotnet-install.ps1 -Channel 8.0 -Runtime windowsdesktop

build_script:
  # --- CORRECTED VERIFICATION ---
  # Verify that the main executable exists in the current directory.
  - cmd: dir SilverBulletPro.exe

artifacts:
  # --- CORRECTED PATH ---
  # Since there is no subfolder, we must package the individual files and folders.
  # We package everything in the current directory.
  - path: '.'
    name: SilverBulletPro-Prepared