# AppVeyor Configuration v5.6 - Production Ready
image: Visual Studio 2022

environment:
  APP_URL: "https://github.com/Izaacapp/SilverBulletPro-Docker/releases/download/blessed/SilverBulletPro-v1.5.8.rar"

install:
  - ps: |
      # Setup isolated workspace
      $workspace = "app_workspace"
      mkdir $workspace | Out-Null
      cd $workspace

      # Download and extract application
      Write-Host "Downloading application package..."
      Invoke-WebRequest -Uri $env:APP_URL -OutFile "app.rar" -UserAgent "AppVeyor"
      7z x app.rar -aoa -y | Out-Null
      Remove-Item app.rar -Force

      # Install runtime dependencies
      Write-Host "Installing .NET 8 Runtime..."
      Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
      ./dotnet-install.ps1 -Channel 8.0 -Runtime windowsdesktop | Out-Null
      Remove-Item dotnet-install.ps1 -Force

build_script:
  - ps: |
      # Comprehensive file verification
      $requiredFiles = @(
        "SilverBulletPro.exe",
        "SilverBulletPro.dll",
        "appsettings.json",
        "nbloader.dll",
        "SilverBulletPro.deps.json",
        "SilverBulletPro.runtimeconfig.json"
      )
      
      Write-Host "Verifying required files..."
      $missing = @()
      foreach ($file in $requiredFiles) {
          if (-not (Test-Path $file)) {
              $missing += $file
              Write-Warning "Missing file: $file"
          }
      }
      
      if ($missing.Count -gt 0) {
          throw "Critical files missing: $($missing -join ', ')"
      }
      
      Write-Host "All required files verified."

artifacts:
  - path: 'app_workspace\*'
    name: SilverBulletPro-Release-Package
    type: Zip