# AppVeyor Configuration v5.7 - Stable Version
image: Visual Studio 2022

environment:
  APP_URL: "https://github.com/Izaacapp/SilverBulletPro-Docker/releases/download/blessed/SilverBulletPro-v1.5.8.rar"

install:
  - ps: |
      # Consistent workspace name
      $workspace = "app_workspace"
      mkdir $workspace | Out-Null
      cd $workspace

      # Download and extract
      Invoke-WebRequest -Uri $env:APP_URL -OutFile "app.rar"
      7z x app.rar -aoa -y | Out-Null
      Remove-Item app.rar -Force

      # Install .NET
      Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
      ./dotnet-install.ps1 -Channel 8.0 -Runtime windowsdesktop | Out-Null
      Remove-Item dotnet-install.ps1 -Force

build_script:
  - ps: |
      # Basic but reliable verification
      $requiredFiles = @(
        "SilverBulletPro.exe",
        "SilverBulletPro.dll",
        "appsettings.json",
        "nbloader.dll",
        "SilverBulletPro.deps.json"
      )
      
      $missingFiles = $requiredFiles | Where-Object { -not (Test-Path $_) }
      if ($missingFiles) {
          throw "Missing files: $($missingFiles -join ', ')"
      }

artifacts:
  # Fixed path that matches the workspace name
  - path: 'app_workspace\*'
    name: SilverBulletPro
    type: Zip