# AppVeyor Configuration v5.2 - Corrected Single-Archive Artifact

image: Visual Studio 2022

environment:
  APP_URL: "https://github.com/Izaacapp/SilverBulletPro-Docker/releases/download/blessed/SilverBulletPro-v1.5.8.rar"

install:
  # Create and enter clean workspace
  - ps: mkdir app_workspace
  - ps: cd app_workspace

  # Download and extract application
  - ps: Invoke-WebRequest -Uri $env:APP_URL -OutFile "app.rar"
  - ps: 7z x app.rar -aoa -y

  # Install .NET Runtime
  - ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
  - ps: ./dotnet-install.ps1 -Channel 8.0 -Runtime windowsdesktop

build_script:
  # Verify executable
  - ps: Test-Path "SilverBulletPro.exe"
  - ps: dir

artifacts:
  # --- THE FINAL CORRECTION ---
  # This tells AppVeyor to take the contents of the 'app_workspace' folder
  # and package them into a single zip file.
  - path: app_workspace
    name: SilverBulletPro-Prepared
    type: Zip