# appveyor.yml - Complete Package Fix
image: Visual Studio 2022

environment:
  APP_URL: "https://github.com/Izaacapp/SilverBulletPro-Docker/releases/download/blessed/SilverBulletPro-v1.5.8.rar"

install:
  - ps: |
      # Create working directory
      mkdir build | Out-Null
      cd build
      
      # Download and extract FULL package
      Invoke-WebRequest -Uri $env:APP_URL -OutFile "app.rar"
      7z x app.rar -aoa -y
      Remove-Item app.rar -Force
      
      # Verify extraction
      if (-not (Test-Path "SilverBulletPro.exe")) {
          throw "Extraction failed - main executable missing!"
      }

artifacts:
  # Package the ENTIRE extracted contents
  - path: 'build\**\*'  # Double star includes all subfolders
    name: SilverBulletPro-Complete
    type: Zip