# appveyor.yml - USB Ready Version
image: Visual Studio 2022

environment:
  APP_URL: "https://github.com/Izaacapp/SilverBulletPro-Docker/releases/download/blessed/SilverBulletPro-v1.5.8.rar"

install:
  - ps: |
      # Create clean workspace
      mkdir SilverBulletPro | Out-Null
      cd SilverBulletPro
      
      # Download and extract full package
      Invoke-WebRequest -Uri $env:APP_URL -OutFile "app.rar"
      7z x app.rar -aoa -y
      Remove-Item app.rar -Force
      
      # Install .NET if missing (for USB use)
      if (-not (Test-Path "$env:ProgramFiles\dotnet\dotnet.exe")) {
          Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
          ./dotnet-install.ps1 -Channel 8.0 -Runtime windowsdesktop
          Remove-Item dotnet-install.ps1 -Force
      }

build_script:
  - ps: |
      # Verify complete package
      $essentials = @('SilverBulletPro.exe', 'Plugins', 'DB', 'Settings')
      $missing = $essentials | Where-Object { -not (Test-Path $_) }
      if ($missing) { throw "Incomplete package! Missing: $($missing -join ', ')" }

artifacts:
  - path: 'SilverBulletPro\*'
    name: SilverBulletPro-USB-Ready
    type: Zip