# AppVeyor Configuration v4.2 - Final
# Corrects the artifact path to account for the nested folder from the .rar archive.

image: Visual Studio 2022

environment:
  APP_URL: "https://github.com/Izaacapp/SilverBulletPro-Docker/releases/download/blessed/SilverBulletPro-v1.5.8.rar"

install:
  - ps: echo "Downloading application..."
  - ps: Invoke-WebRequest -Uri $env:APP_URL -OutFile "app.rar"
  - ps: echo "Extracting application..."
  - ps: 7z x app.rar -aoa -y
  - ps: echo "Installing .NET 8 Desktop Runtime..."
  - ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'
  - ps: ./dotnet-install.ps1 -Channel 8.0 -Runtime windowsdesktop

build_script:
  - cmd: echo "Setup complete. Verifying extracted folder..."
  # We will now check the nested path to confirm it exists
  - cmd: dir SilverBulletPro-v1.5.8\SilverBulletPro-v1.5.8

artifacts:
  # --- THIS IS THE CORRECTED PATH ---
  # Point to the actual location of the application files.
  - path: 'SilverBulletPro-v1.5.8\SilverBulletPro-v1.5.8'
    name: SilverBulletPro-Prepared